on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus IQ Policy Evaluation
      run: |
        # Install Nexus IQ CLI
        curl -o nexus-iq-cli-1.164.0-01+657-unix.zip https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/scanner/nexus-iq-cli-1.164.0-01+657-unix.zip
        unzip nexus-iq-cli-1.164.0-01+657-unix.zip
        export PATH=$PATH:$(pwd)/nexus-iq-cli/bin

        # Run Nexus IQ scan
        ./nexus-iq-cli \
          -s http://192.168.15.101:8070 \
          -a admin:Xmart2022 \
          -i webgoat \
          -d ./target \
          -r results.json

        # Process the scan results
        cat results.json
#a