on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus IQ Policy Evaluation
      run: |
        # Install Nexus IQ CLI
        curl -o nexus-iq-cli.zip https://download.sonatype.com/clm/scanner/latest.zip
        unzip nexus-iq-cli.zip
        export PATH=$PATH:$(pwd)/nexus-iq-cli/bin

        # Run Nexus IQ scan
        nexus-iq-cli -s http://192.168.15.101:8070 \
          -a admin \
          -p Xmart2022 \
          -i webgoat \
          -t ./Webgoat-1 \
          -r results.json

        # Process the scan results
        cat results.json
